export enum InfringementsEnum {
    GET_INFRINGEMENTS_DATES = 'GET_INFRINGEMENTS_DATES',
    SET_PAGINATION_DATA = 'SET_PAGINATION_DATA',
    GET_INFRINGEMENTS_DATES_FOR_GRAPH = 'GET_INFRINGEMENTS_DATES_FOR_GRAPH',
}